/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import dao.AgendamentoDao;
import dao.CadastroDao;
import dao.ServicosDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.table.DefaultTableModel;
import models.AgendamentoModel;
import models.CadastroModel;
import models.ServicosModel;

/**
 *
 * @author marcu
 */
public class Agendamento extends javax.swing.JFrame {
    int contador=0;
    /**
     * Creates new form Agendamento
     */
    public Agendamento() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(255, 204,255));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CampoID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        butaoCadastrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CampoCPF = new javax.swing.JFormattedTextField();
        butaoLimpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaAgendamento = new javax.swing.JTable();
        CampoHorario = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CampoNome = new javax.swing.JComboBox<>();
        CampoServico = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CampoTelefone = new javax.swing.JFormattedTextField();
        jVoltar = new javax.swing.JButton();
        jFormattedCampoData = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("ID do Cliente");

        CampoID.setEditable(false);
        CampoID.setBackground(new java.awt.Color(204, 204, 204));
        CampoID.setForeground(new java.awt.Color(153, 153, 153));
        CampoID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        CampoID.setBorder(null);
        CampoID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CampoID.setFocusable(false);
        CampoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoIDActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel2.setText("Nome:");

        butaoCadastrar.setBackground(new java.awt.Color(204, 102, 255));
        butaoCadastrar.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        butaoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        butaoCadastrar.setText("CADASTRAR");
        butaoCadastrar.setActionCommand("CADASTRAR");
        butaoCadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 255), 5));
        butaoCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butaoCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butaoCadastrarMouseClicked(evt);
            }
        });
        butaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoCadastrarActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Telefone:");

        CampoCPF.setBackground(new java.awt.Color(255, 255, 255));
        CampoCPF.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        CampoCPF.setForeground(new java.awt.Color(0, 0, 0));
        try {
            CampoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CampoCPF.setName(""); // NOI18N
        CampoCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoCPFKeyTyped(evt);
            }
        });

        butaoLimpar.setBackground(new java.awt.Color(204, 102, 255));
        butaoLimpar.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        butaoLimpar.setForeground(new java.awt.Color(255, 255, 255));
        butaoLimpar.setText("LIMPAR CAMPOS");
        butaoLimpar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 5, true));
        butaoLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butaoLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butaoLimparMouseClicked(evt);
            }
        });
        butaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoLimparActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setText("Horario:");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("CPF:");

        TabelaAgendamento.setBackground(new java.awt.Color(204, 204, 255));
        TabelaAgendamento.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        TabelaAgendamento.setForeground(new java.awt.Color(102, 102, 102));
        TabelaAgendamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Telefone", "Data", "Horario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAgendamento.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TabelaAgendamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabelaAgendamento.setGridColor(new java.awt.Color(204, 204, 255));
        TabelaAgendamento.setSelectionBackground(new java.awt.Color(255, 204, 255));
        TabelaAgendamento.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TabelaAgendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaAgendamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaAgendamento);
        if (TabelaAgendamento.getColumnModel().getColumnCount() > 0) {
            TabelaAgendamento.getColumnModel().getColumn(0).setResizable(false);
            TabelaAgendamento.getColumnModel().getColumn(1).setResizable(false);
            TabelaAgendamento.getColumnModel().getColumn(2).setResizable(false);
            TabelaAgendamento.getColumnModel().getColumn(3).setResizable(false);
            TabelaAgendamento.getColumnModel().getColumn(4).setResizable(false);
            TabelaAgendamento.getColumnModel().getColumn(5).setResizable(false);
        }

        CampoHorario.setBackground(new java.awt.Color(255, 255, 255));
        CampoHorario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        CampoHorario.setForeground(new java.awt.Color(0, 0, 0));
        try {
            CampoHorario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Data:");

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("AGENDAMENTO DE CLIENTES");

        CampoNome.setBackground(new java.awt.Color(255, 204, 204));
        CampoNome.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        CampoNome.setForeground(new java.awt.Color(51, 51, 51));
        CampoNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 3, true));
        CampoNome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        CampoServico.setBackground(new java.awt.Color(255, 204, 204));
        CampoServico.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        CampoServico.setForeground(new java.awt.Color(51, 51, 51));
        CampoServico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 3, true));
        CampoServico.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel6.setText("Serviço:");

        CampoTelefone.setBackground(new java.awt.Color(255, 255, 255));
        CampoTelefone.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        CampoTelefone.setForeground(new java.awt.Color(0, 0, 0));
        try {
            CampoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CampoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefoneActionPerformed(evt);
            }
        });

        jVoltar.setBackground(new java.awt.Color(204, 102, 255));
        jVoltar.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N
        jVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jVoltar.setText("VOLTAR");
        jVoltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 5, true));
        jVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVoltarMouseClicked(evt);
            }
        });
        jVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVoltarActionPerformed(evt);
            }
        });

        jFormattedCampoData.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        try {
            jFormattedCampoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedCampoData.setToolTipText("");
        jFormattedCampoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedCampoDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(butaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(butaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CampoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jFormattedCampoData, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CampoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(CampoID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(CampoCPF))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CampoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(138, 138, 138)))
                            .addComponent(jVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CampoID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CampoCPF)
                            .addComponent(CampoTelefone))
                        .addGap(14, 14, 14)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedCampoData, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(butaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //vo arruma depois
    private void butaoCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaoCadastrarMouseClicked
       if(CampoCPF.getText().trim().isEmpty() || 
          CampoTelefone.getText().trim().isEmpty() || 
          jFormattedCampoData.getText().trim().isEmpty() || 
          CampoHorario.getText().trim().isEmpty())
          {
                   JOptionPane.showMessageDialog(null, "Nenhum dado idendificado");
                   CampoNome.requestFocus();
       }else{
            if (contador == 0) {            
                try{    
                   AgendamentoModel cadastroP = new AgendamentoModel();
                   
                  cadastroP.setNome(CampoNome.getSelectedItem().toString());
                  cadastroP.setCpf(CampoCPF.getText());
                  cadastroP.setTelefone(CampoTelefone.getText());
                  cadastroP.setServico(CampoServico.getSelectedItem().toString());  
                  cadastroP.setDataAgendamento(jFormattedCampoData.getText());
                  cadastroP.setHorario(CampoHorario.getText());
                  
                  AgendamentoDao cadastroPDao = new AgendamentoDao();
                  cadastroPDao.inserir(cadastroP); 
                  limparTabela();
                  atualizaTabela(cadastroPDao);
                  JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso!", "", INFORMATION_MESSAGE);
                  limparCampos();
                }
                catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
                } 
            }else{
                AgendamentoModel cadastroP = new AgendamentoModel();
                  cadastroP.setNome(CampoNome.getSelectedItem().toString());
                  cadastroP.setCpf(CampoCPF.getText());
                  cadastroP.setTelefone(CampoTelefone.getText());
                  cadastroP.setServico(CampoServico.getSelectedItem().toString());  
                  cadastroP.setDataAgendamento(jFormattedCampoData.getText());
                  cadastroP.setHorario(CampoHorario.getText());

                AgendamentoDao cadastroPDao = new AgendamentoDao();
                cadastroPDao.alterar(cadastroP);
                limparTabela();
                atualizaTabela(cadastroPDao);
                JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!", "", INFORMATION_MESSAGE);
                CampoNome.requestFocus();
                limparCampos();
                
                contador = 0;
                TabelaAgendamento.setVisible(true);
                butaoCadastrar.setText("Cadastrar");                
            }    

       }
       
    }//GEN-LAST:event_butaoCadastrarMouseClicked

    private void butaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butaoCadastrarActionPerformed

    private void CampoCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoCPFKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CampoCPFKeyTyped

    private void butaoLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaoLimparMouseClicked
        limparCampos();
    }//GEN-LAST:event_butaoLimparMouseClicked
    
    private void limparUser(){
        CampoNome.removeAllItems();
    }
    
    private void limparServico(){
        CampoServico.removeAllItems();
    }
    
    private void limparCampos(){
        this.CampoNome.setSelectedIndex(-1);
        this.CampoID.setText("");
        this.CampoCPF.setText("");
        this.CampoTelefone.setText("");
        this.jFormattedCampoData.setText("");
        this.CampoHorario.setText("");
    }
  
    private void limparTabela(){
        //percorre a tabela e exclui todas as linhas
        while(TabelaAgendamento.getRowCount() > 0){
            DefaultTableModel dm = (DefaultTableModel) TabelaAgendamento.getModel();
            dm.getDataVector().removeAllElements();
        }
    }
    
    private void atualizaTabela(AgendamentoDao cadastroPDao){
        try{
                    limparTabela();

                    ArrayList<AgendamentoModel> listaCadastros;
                    listaCadastros = cadastroPDao.consultar();        
                    DefaultTableModel modeloTabela = (DefaultTableModel) TabelaAgendamento.getModel();

                    for (AgendamentoModel cadastroP : listaCadastros) {
    modeloTabela.addRow(new String[]{
        String.valueOf(cadastroP.getIdAgendamento()),
        cadastroP.getNome(),
        cadastroP.getCpf(),
        cadastroP.getTelefone(),
        cadastroP.getDataAgendamento(),
        cadastroP.getHorario(),     
        String.valueOf(cadastroP.getIdServico()),
        String.valueOf(cadastroP.getIdCliente())
    });
                    } 
                }
                catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
                }
     
        }
    
    
    private void atualizaTabelaUsers(CadastroDao DaoFunc){
        try{
              limparUser();
              ArrayList<CadastroModel> listarFunc;
              listarFunc = DaoFunc.consultar();

              for(CadastroModel func : listarFunc){
                  CampoNome.addItem(func.getNome());
               }
                    CampoNome.setSelectedIndex(-1);
                    }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
                    }
                
    }
    
    private void atualizaTabelaServicos(ServicosDao DaoFunc){
        try{
              limparServico();
              ArrayList<ServicosModel> listarFunc;
              listarFunc = DaoFunc.consultar();

              for(ServicosModel func : listarFunc){
                  CampoServico.addItem(func.getServico());
               }
                    CampoServico.setSelectedIndex(-1);
                    }catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
                    }
                
    }

    private void butaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butaoLimparActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        AgendamentoDao attagenda = new AgendamentoDao();
        atualizaTabela(attagenda);
        
        ServicosDao attServicos = new ServicosDao();
        atualizaTabelaServicos(attServicos);
        
        CadastroDao attUsers = new CadastroDao();
        atualizaTabelaUsers(attUsers); 
    }//GEN-LAST:event_formWindowOpened

    private void CampoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoIDActionPerformed

    private void TabelaAgendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaAgendamentoMouseClicked
        if((TabelaAgendamento.getSelectedRow() != -1) && (contador == 0) && (evt.getClickCount() == 2)){
           CampoID.setText(TabelaAgendamento.getValueAt(TabelaAgendamento.getSelectedRow(),0).toString());
           CampoNome.setSelectedItem(TabelaAgendamento.getValueAt(TabelaAgendamento.getSelectedRow(),1).toString());
           CampoCPF.setText(TabelaAgendamento.getValueAt(TabelaAgendamento.getSelectedRow(),2).toString());
           CampoTelefone.setText(TabelaAgendamento.getValueAt(TabelaAgendamento.getSelectedRow(), 3).toString()); 
           CampoServico.setSelectedItem(TabelaAgendamento.getValueAt(TabelaAgendamento.getSelectedRow(),4).toString());
           jFormattedCampoData.setText(TabelaAgendamento.getValueAt(TabelaAgendamento.getSelectedRow(), 4).toString()); 
           CampoHorario.setText(TabelaAgendamento.getValueAt(TabelaAgendamento.getSelectedRow(), 4).toString()); 
           contador = 1;
           TabelaAgendamento.enable(false);
           butaoCadastrar.setText("Alterar");
        }   
    }//GEN-LAST:event_TabelaAgendamentoMouseClicked

    private void jVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVoltarActionPerformed

    private void jVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVoltarMouseClicked
         Inicio frameInicio = new Inicio();
         frameInicio.setVisible(true);
         this.dispose();
        
    }//GEN-LAST:event_jVoltarMouseClicked

    private void jFormattedCampoDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedCampoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedCampoDataActionPerformed

    private void CampoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CampoCPF;
    private javax.swing.JFormattedTextField CampoHorario;
    private javax.swing.JTextField CampoID;
    private javax.swing.JComboBox<String> CampoNome;
    private javax.swing.JComboBox<String> CampoServico;
    private javax.swing.JFormattedTextField CampoTelefone;
    private javax.swing.JTable TabelaAgendamento;
    private javax.swing.JButton butaoCadastrar;
    private javax.swing.JButton butaoLimpar;
    private javax.swing.JFormattedTextField jFormattedCampoData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jVoltar;
    // End of variables declaration//GEN-END:variables
}
