/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import dao.ServicosDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.table.DefaultTableModel;
import models.ServicosModel;

/**
 *
 * @author marcu
 */
public class Servicos extends javax.swing.JFrame {
    int contador=0;
    /**
     * Creates new form Servicos
     */
    public Servicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butaoCadastrar = new javax.swing.JButton();
        CampoServico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        butaoExcluir = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaServicos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CampoProfissional = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        butaoCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        butaoCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        butaoCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        butaoCadastrar.setText("Cadastrar");
        butaoCadastrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 5, true));
        butaoCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butaoCadastrarMouseClicked(evt);
            }
        });
        butaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butaoCadastrarActionPerformed(evt);
            }
        });

        CampoServico.setBackground(new java.awt.Color(255, 255, 255));
        CampoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoServicoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("Serviços");

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Nome do Serviço");

        butaoExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butaoExcluirMouseClicked(evt);
            }
        });

        TabelaServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome do Serviço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaServicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaServicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaServicos);

        jLabel1.setText("Nome do Profissional");

        CampoProfissional.setBackground(new java.awt.Color(255, 255, 255));
        CampoProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoProfissionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(butaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(CampoProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(butaoExcluir))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butaoCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaoCadastrarMouseClicked
        // TODO add your handling code here:
        if(((CampoServico.getText().trim().isEmpty()))){
            JOptionPane.showMessageDialog(null, "Nenhum dado idendificado");
            CampoServico.requestFocus();
        }else{
            if (contador == 0) {
                try{
                    ServicosModel cadastroP = new ServicosModel();

                    cadastroP.setServico(CampoServico.getText());
                    cadastroP.setNomeProfissional(CampoProfissional.getText());
                    
                    ServicosDao cadastroPDao = new ServicosDao();
                    cadastroPDao.inserir(cadastroP);
                    limparTabela();
                    atualizaTabela(cadastroPDao);
                    JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso!", "", INFORMATION_MESSAGE);
                    limparCampos();
                }
                catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
                }
            }else{
                ServicosModel cadastroP = new ServicosModel();
                //cadastroP.setID(Integer.parseInt(CampoID.getText()));
                cadastroP.setServico(CampoServico.getText());
                cadastroP.setNomeProfissional(CampoProfissional.getText());

                ServicosDao cadastroPDao = new ServicosDao();
                cadastroPDao.alterar(cadastroP);
                limparTabela();
                atualizaTabela(cadastroPDao);
                JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso!", "", INFORMATION_MESSAGE);
                CampoServico.requestFocus();
                limparCampos();

                contador = 0;
                TabelaServicos.setVisible(true);
                butaoCadastrar.setText("Cadastrar");
            }

        }
    }//GEN-LAST:event_butaoCadastrarMouseClicked

    private void butaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butaoCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butaoCadastrarActionPerformed

    private void butaoExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butaoExcluirMouseClicked
        if(TabelaServicos.getSelectedRow() != -1){
            int msgRetorno = JOptionPane.showConfirmDialog(null,
                "Confirme para remover o cadastro",
                "Confirmação",
                JOptionPane.YES_NO_OPTION);
            if (msgRetorno == JOptionPane.YES_OPTION) {
                //int ID = Integer.parseInt(CampoID.getText());
                DefaultTableModel tabelacadastro = (DefaultTableModel) TabelaServicos.getModel();
                tabelacadastro.removeRow((TabelaServicos.getSelectedRow()));

                ServicosDao deleteitem = new ServicosDao();
                //deleteitem.excluirID(ID);
                butaoCadastrar.setText("Cadastrar");
                limparCampos();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Cadastro para excluir!");
        }
    }//GEN-LAST:event_butaoExcluirMouseClicked

    private void TabelaServicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaServicosMouseClicked
        if((TabelaServicos.getSelectedRow() != -1) && (contador == 0) && (evt.getClickCount() == 2)){
            //CampoID.setText(TabelaServicos.getValueAt(TabelaServicos.getSelectedRow(),0).toString());
            CampoServico.setText(TabelaServicos.getValueAt(TabelaServicos.getSelectedRow(),1).toString());
            contador = 1;
            TabelaServicos.enable(false);
            butaoCadastrar.setText("Alterar");
        }
    }//GEN-LAST:event_TabelaServicosMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ServicosDao attServicos = new ServicosDao();
        atualizaTabela(attServicos);
    }//GEN-LAST:event_formWindowOpened

    private void CampoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoServicoActionPerformed

    private void CampoProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoProfissionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoProfissionalActionPerformed
    
    private void limparCampos(){
        //this.CampoID.setText("");
        this.CampoServico.setText("");
        }
    
    private void limparTabela(){
        while(TabelaServicos.getRowCount() > 0){
            DefaultTableModel dm = (DefaultTableModel) TabelaServicos.getModel();
            dm.getDataVector().removeAllElements();
        }
    }
    
    private void atualizaTabela(ServicosDao cadastroPDao){
        try{
                    limparTabela();

                    ArrayList<ServicosModel> listaCadastros;
                    listaCadastros = cadastroPDao.consultar();        
                    DefaultTableModel modeloTabela = (DefaultTableModel) TabelaServicos.getModel();

                    for(ServicosModel cadastroP : listaCadastros){
                        modeloTabela.addRow(new String[]{Integer.toString(cadastroP.getID()),cadastroP.getServico()});
                    }

                }
                catch(Exception ex){
                    JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado na linha 275:\n" + ex.getMessage(), "ERRO!", ERROR_MESSAGE);
                }
     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoProfissional;
    private javax.swing.JTextField CampoServico;
    private javax.swing.JTable TabelaServicos;
    private javax.swing.JButton butaoCadastrar;
    private javax.swing.JLabel butaoExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
